/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#a2c9ff",
        "on-tertiary-fixed-variant": "#41474e",
        "primary-fixed": "#d6e3ff",
        "on-tertiary": "#ffffff",
        "on-surface": "#0b1c30",
        "secondary-fixed": "#d3e4ff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "surface-bright": "#f8f9ff",
        "tertiary": "#1b2127",
        "surface-tint": "#455f88",
        "on-background": "#0b1c30",
        "primary": "#002045",
        "secondary": "#1960a3",
        "error": "#ba1a1a",
        "on-primary-container": "#86a0cd",
        "background": "#f8f9ff",
        "on-primary-fixed": "#001b3c",
        "tertiary-container": "#30363c",
        "outline-variant": "#c4c6cf",
        "tertiary-fixed-dim": "#c1c7cf",
        "tertiary-fixed": "#dde3eb",
        "surface-variant": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#00477f",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed": "#161c22",
        "surface": "#f8f9ff",
        "on-surface-variant": "#43474e",
        "on-secondary-fixed-variant": "#004881",
        "secondary-container": "#7db6ff",
        "outline": "#74777f",
        "on-tertiary-container": "#989fa6",
        "surface-container-highest": "#d3e4fe",
        "on-primary-fixed-variant": "#2d476f",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#1a365d",
        "surface-container-high": "#dce9ff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-container": "#e5eeff",
        "primary-fixed-dim": "#adc7f7",
        "inverse-primary": "#adc7f7",
        "on-secondary-fixed": "#001c38",
        "surface-container-low": "#eff4ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        mono: ["Courier Prime", "monospace"],
      }
    },
  },
  plugins: [],
}
